# - - å¤´åƒ
avatar:
  enable: true
  url: https://raw.githubusercontent.com/god23bin/pic-bed/master/img/20220516145418.jpeg
  rounded: true
  opacity: 1
  mickey_mouse: true
  status:
    enable: true
    emoji: ğŸ˜†
    message: ä»Šå¤©ä¸å­¦ä¹ ï¼Œæ˜å¤©å˜åƒåœ¾

# ä¸»é¢˜é…ç½®
# - ä¸»é¢˜è‰² åˆ†æå·¥å…· https://www.yunyoujun.cn/color-dust
colors:
  primary: "#6200ee"
  # èƒŒæ™¯è‰²ï¼ˆé€‰å–ä¸ä½ çš„èƒŒæ™¯å›¾ç‰‡ä¸»è‰²è°ƒæ›´è´´è¿‘çš„é¢œè‰²æ¥ä½¿å…¶æ›´åè°ƒï¼‰
  # bg: "#F5F5F5"
  selection_bg: "#8e71c1" # é€‰å–æ–‡å­—æ—¶çš„èƒŒæ™¯è‰²
  # æ ‡ç­¾äº‘ä¸­æ ‡ç­¾çš„èµ·å§‹è‰²å’Œç»“æŸè‰²
  # tag_start_color:
  # tag_end_color:

# - - ä¸ºæ ‡ç­¾æŒ‡å®šå½©è‰²ï¼Œé»˜è®¤#333
tags:
  Vue: "#4fc08d"
  Hexo: "#0E834D"
  CSS: "#5298d1"
  Node.js: "#026E00"
  Git: "#F14E32"
  React: "#61dafb"
  Python: "#3776ab"
  PHP: "#8892BF"
  VS Code: "#0066B8"
  JavaScript: "#F4DF4F"
  TypeScript: "#317AC6"
  Laravel: "#F4645F"
  
  
# - - ä¸ºåˆ†ç±»æŒ‡å®šå½©è‰²ï¼Œé»˜è®¤#333
categories:
  è®°å½•: dimgray

# ï¼ˆç¡®ä¿ä½ çš„ favicon.ico æ–‡ä»¶å·²æ”¾ç½®äº source æ–‡ä»¶å¤¹ä¸‹ï¼‰
favicon: /favicon.ico


# - ç¤¾äº¤å›¾æ ‡
social:
#  - name: RSS
#    # set rss in your root config
#    # https://github.com/hexojs/hexo-generator-feed
#    link: /atom.xml # config.feed.path
#    icon: icon-rss-line
#    color: orange
#  - name: QQ
#    # https://isux.tencent.com/wp-content/uploads/2016/05/20160512101222609.pdf
#    link: https://wpa.qq.com/msgrd?v=3&uin=910426929&site=qq&menu=yes
#    icon: icon-qq-line
#    color: "#12B7F5"
  - name: GitHub
    link: https://github.com/god23bin
    icon: icon-github-line
    color: "#181717"
  - name: E-Mail
    link: god23bin@qq.com
    icon: icon-mail-line
    color: "#8E71C1"
  - name: ç½‘æ˜“äº‘éŸ³ä¹
    link: https://music.163.com/#/user/home?id=77844313
    icon: icon-netease-cloud-music-line
    color: "#C10D0C"
#  - name: çŸ¥ä¹
#    link: https://www.zhihu.com/people/yunyoujun/
#    icon: icon-zhihu-line
#    color: "#0084FF"
  - name: å“”å“©å“”å“©åŠ¨ç”»
    link: https://space.bilibili.com/341183781
    icon: icon-bilibili-line
    color: "#FF8EB3"
#  - name: å¾®ä¿¡å…¬ä¼—å·
#    link: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/about/white-qrcode-and-search.jpg
#    icon: icon-wechat-2-line
#    color: "#1AAD19"


# - é¦–é¡µ
# - - æ ‡è¯­åŠ¨ç”»
banner:
  enable: true
  title: 
    - æ–¹åœ†
    - å¯æ–¹
    - å¯åœ†
  border: true
  cloud:
    enable: true
    color: "white"
  go_down:
    enable: true
    icon: icon-arrow-down-s-line

# - - å…¬å‘Š
notice:
  enable: true
  content: å¯çˆ±çš„ä½ æ¥å•¦ï¼
  
# å¯é€‰ light | dark | auto | time
mode: auto

# - - å­—ä½“
font:
  cdn:
    enable: true
    lib:
      - https://fonts.googleapis.com/css2?family=Noto+Serif+SC:wght@900&display=swap
  serif:
    family: "'Songti SC', 'Noto Serif SC', STZhongsong, STKaiti, KaiTi, Roboto, serif"
    weight: 900
  sans_serif:
    family: "'PingFang SC', 'Microsoft YaHei', Roboto, Arial, sans-serif"
    weight: 400
  monospace:
    family: "'Source Code Pro', 'Courier New', Courier, Consolas, Monaco, monospace"


# - - å›¾ç‰‡èƒŒæ™¯
bg_image:
  enable: true
  url: /images/bg3.jpg
  dark: /images/bg1.jpg
  # blur: 30px # è®¾ç½®èƒŒæ™¯æ¨¡ç³Šç¨‹åº¦
  opacity: 0.8

# - - ç‚¹å‡»é¡µé¢çš„çƒŸèŠ±æ•ˆæœ
fireworks:
  enable: true
  colors:
    - "102, 167, 221"
    - "62, 131, 225"
    - "33, 78, 194"
    
# - - å…‰æ ‡
cursor:
  enable: true
  default: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/css/md-cursors/pointer.cur
  pointer: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/css/md-cursors/link.cur
  text: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/css/md-cursors/text.cur

# ä¾§è¾¹æ 
# - - èƒŒæ™¯ä¸æ ‡ç­¾
#     - tagcloud: åœ¨ä¾§è¾¹æ æ˜¾ç¤º Hexo åŸç”Ÿæ ‡ç­¾é¡µ
#       - amount: æ˜¾ç¤ºçš„æ ‡ç­¾æ•°é‡
sidebar:
  #bg_image: https://gitee.com/god23bin/blog-pic-bed/raw/master/1562893544881.jpg
  bg_image: /images/sidebar_bg.jpg
  bg_position: center
  tagcloud:
    enable: true
    amount: 20

# - - å¯¼èˆª
# è®¾ç½®å¯¼èˆªå¯¹åº”å›¾æ ‡åŠé“¾æ¥
# 
# åˆ†åˆ«ä¸ºï¼š
# 
# ä¸»é¡µ
# åˆ—è¡¨
#   å½’æ¡£
#   æ ‡ç­¾
#   åˆ†ç±»
# è‡ªå®šä¹‰ï¼ˆä½ å¯ä»¥è®¾ç½®ä¸ºä»»æ„å›¾æ ‡åŠé“¾æ¥ï¼Œå½“ä½ æœªè®¾ç½®è‡ªå®šä¹‰å›¾æ ‡é“¾æ¥æ—¶ï¼Œå®ƒå°†è‡ªåŠ¨å˜ä¸ºæ–‡æ¡£å¯¼èˆªæŒ‰é’®ä»¥ä¿æŒæ•´ä½“çš„å¯¹ç§°ï¼‰
menu:
  home:
    path: /
    icon: icon-home-4-line
  list:
    - type: archives
      path: /archives/
      icon: icon-archive-line
    - type: categories
      path: /categories/
      icon: icon-folder-2-line
    - type: tags
      path: /tags/
      icon: icon-price-tag-3-line
    # - path: https://www.yunyoujun.cn
    #   icon: icon-cloud-line
    #   count: ä½ çŒœ
  custom:
    title: æ–‡æ¡£
    path: https://yun.yunyoujun.cn
    icon: icon-settings-line


# - - é¡µé¢é“¾æ¥
# åœ¨ sidebar çš„æœ€ä¸‹æ–¹ï¼Œæ·»åŠ é†’ç›®çš„å›¾æ ‡é“¾æ¥ã€‚
# ç›¸æ¯”ç¤¾äº¤é“¾æ¥ï¼Œå›¾æ ‡æ›´å¤§ã€‚ä½ å¯ä»¥æ”¾ç½®ä½ çš„é¡µé¢å¯¼èˆªï¼Œå‹æƒ…é“¾æ¥ç­‰ã€‚

pages:
  - name: æˆ‘å–œæ¬¢çš„å¤§ä½¬ä»¬
    url: /links/
    icon: icon-genderless-line
    color: dodgerblue
  - name: æˆ‘çš„å¥³ç¥å¤©ä½¿ä»¬
    url: /girls/
    icon: icon-women-line
    color: dodgerblue

girls:
  enable: true

# - æ–‡ç« 
# - - å†…å®¹å¡ç‰‡
post_card:
  opacity: 0.8
  
# - - æ–‡ç« ä¿¡æ¯
post_meta:
  item_text: false
  created_at: true
  updated_at: true
  categories: true
  tags: true

# - - æ–‡ç« ç›®å½•
toc:
  # æ˜¾ç¤ºç¼–å·
  list_number: false
  max_depth: 6
  min_depth: 1
  placeholder: å¾ˆé—æ†¾ï¼Œå’±æ²¡å†™å•¥ç›®å½•
  collapse: false

# - - æ–‡ç« ç¼–è¾‘è¿æ¥
post_edit:
  enable: false
  url: https://github.com/god23bin/god23bin.github.io/tree/hexo/source/

# - - ä»£ç é«˜äº®
# è¿˜éœ€åœ¨ Hexo ï¼ˆé¡»å‡çº§è‡³ 5.0 ä»¥ä¸Šç‰ˆæœ¬ï¼‰å·¥ä½œç›®å½•ä¸‹çš„ _config.yml ä¸­é…ç½®
codeblock:
  copy_btn: true
  prismjs:
    light: default
    dark: tomorrow

# - - ç‰ˆæƒ
# ä½ çš„ url è¯·åœ¨ Hexo å·¥ä½œç›®å½•ä¸‹çš„ _config.yml ä¸­è®¾ç½®
creative_commons:
  license: by-nc-sa
  post: true
  language: deed.zh
  clipboard: true

# - æ‰“èµ
# - - æ‰“èµäºŒç»´ç 
# æ‰“èµ
reward:
  enable: true
  icon: icon-hand-coin-line
  comment: é“ä»”oré“å¥³ï¼Œå¯ä»¥è¯·æˆ‘å–æ¯å’–å•¡å—ï¼Ÿ.
  # url: https://github.com/YunYouJun/yunyoujun.github.io/issues/96
  methods:
    - name: æ”¯ä»˜å®
      path: https://gitee.com/god23bin/blog-pic-bed/raw/master/img/20210405133621.png
      color: "#00A3EE"
      icon: icon-alipay-line
#    - name: QQ æ”¯ä»˜
#      path: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/donate/qqpay-qrcode.png
#      color: "#12B7F5"
#      icon: icon-qq-line
    - name: å¾®ä¿¡æ”¯ä»˜
      path: https://gitee.com/god23bin/blog-pic-bed/raw/master/img/20210405133651.png
      color: "#2DC100"
      icon: icon-wechat-pay-line


# - é¡µè„š
footer:
  since: 2021
  icon:
    name: icon-cloud-line
    animated: true
    color: "#0078E7"
  powered:
    enable: true
  live_time:
    enable: true
    prefix: æœ¬åšå®¢å·²èŒèŒå“’åœ°è¿è¡Œ
    suffix: (â—'â—¡'â—)
    start_time: "2021-04-01T00:00:00"


say:
  enable: true
  api: https://cdn.jsdelivr.net/gh/ElpsyCN/say@gh-pages/sentences.json
  src: /js/say.js
  # https://developer.hitokoto.cn/sentence/
  hitokoto:
    enable: true
    api: https://v1.hitokoto.cn


mourn:
  enable: true
  days:
    - "4-4"

# å­—æ•°ç»Ÿè®¡
# npm install hexo-wordcount
wordcount:
  enable: true
  count: true
  time: true

# æ ‡ç­¾äº‘
wordcloud:
  enable: true
  height: 350


# æ•°å­¦å…¬å¼ KaTeX
katex:
  copy_tex: true
  global: true


# å…¨å±€æ’­æ”¾å™¨
aplayer:
  global: true
  meting: true
  # https://github.com/metowolf/MetingJS/tree/v1.2#option
  widget:
    enable: true
    autoplay: true
    # theme: "#2980b9"
    loop: all
    order: list
    volume: 0.7
    mutex: true
    lrcType: 0
    listFolded: false
    listMaxHeight: 340px
    meting:
      enable: true
      id: 140834718
      server: netease
      type: playlist

pjax:
  enable: true

busuanzi:
  enable: true
  site_uv: true
  site_uv_icon: icon-user-line
  site_pv: true
  site_pv_icon: icon-eye-line
  page_pv: true
  page_pv_icon: icon-eye-line

